# Generated by Django 2.2 on 2021-01-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='CourseComments',
        ),
    ]
