# Generated by Django 2.2 on 2021-01-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndRegistration', '0001_initial'),
        ('Courses', '0002_auto_20210125_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(related_name='course', to='LoginAndRegistration.User'),
        ),
    ]
